test_that("du_dmu works", {
  #need to set inversion tolerance to, eg, 10^-16 for this to pass
  source("../../misc/diffusion.R")
  load("../../misc/setup.RData")
  for (diffusionType in -1:1){
    du_dmu0=du_dmu(mu_0,
                   alpha,
                   gamma,
                   longLat,
                   sigma,
                   kappa,
                   coords,
                   X_diffusion,
                   X_reaction,
                   rows-2,
                   cols-2,
                   nTime,
                   diffusionType,
                   TRUE,
                   lengthX,
                   lengthY,
                   TRUE)
    
    step=0.00000001
    
    u0=computeDiffusion(mu_0-step,
                        alpha,
                        gamma,
                        longLat,
                        sigma,
                        kappa,
                        coords,
                        X_diffusion,
                        X_reaction,
                        rows-2,
                        cols-2,
                        nTime,
                        diffusionType,
                        TRUE,
                        lengthX,
                        lengthY,
                        TRUE)
    u1=computeDiffusion(mu_0+step,
                        alpha,
                        gamma,
                        longLat,
                        sigma,
                        kappa,
                        coords,
                        X_diffusion,
                        X_reaction,
                        rows-2,
                        cols-2,
                        nTime,
                        diffusionType,
                        TRUE,
                        lengthX,
                        lengthY,
                        TRUE)
    du_dmu1=(u1-u0)/(2*step)

    expect_equal(du_dmu0[[1]],du_dmu1,tol=4*sqrt(.Machine$double.eps))
    
    for (i in 1:ncol(X_diffusion)){
      step=0.000001
      
      alpha0=alpha
      alpha1=alpha
      alpha0[i]=alpha0[i]-step
      alpha1[i]=alpha1[i]+step
      u0=computeDiffusion(mu_0,
                          alpha0,
                          gamma,
                          longLat,
                          sigma,
                          kappa,
                          coords,
                          X_diffusion,
                          X_reaction,
                          rows-2,
                          cols-2,
                          nTime,
                          diffusionType,
                          TRUE,
                          lengthX,
                          lengthY,
                          TRUE)
      u1=computeDiffusion(mu_0,
                          alpha1,
                          gamma,
                          longLat,
                          sigma,
                          kappa,
                          coords,
                          X_diffusion,
                          X_reaction,
                          rows-2,
                          cols-2,
                          nTime,
                          diffusionType,
                          TRUE,
                          lengthX,
                          lengthY,
                          TRUE)
      du_dmu1=(u1-u0)/(2*step)
      expect_equal(du_dmu0[[1+i]],du_dmu1,tol=4*sqrt(.Machine$double.eps))
    }
  }
})
