test_that("du_dsigma works", {
  source("../../misc/diffusion.R")
  load("../../misc/setup.RData")
  du_dsigma0=du_dsigma(mu_0,
                       gamma,
                       longLat,
                       sigma,
                       kappa,
                       coords,
                       X_reaction,
                       rows-2,
                       cols-2,
                       nTime,
                       diffusionType,
                       TRUE,
                       lengthX,
                       lengthY,
                       TRUE)
  
  step=0.0001
  
  u0=computeDiffusion(mu_0,
                      gamma,
                      longLat,
                      sigma-step,
                      kappa,
                      coords,
                      X_reaction,
                      rows-2,
                      cols-2,
                      nTime,
                      diffusionType,
                      TRUE,
                      lengthX,
                      lengthY,
                      TRUE)
  u1=computeDiffusion(mu_0,
                      gamma,
                      longLat,
                      sigma+step,
                      kappa,
                      coords,
                      X_reaction,
                      rows-2,
                      cols-2,
                      nTime,
                      diffusionType,
                      TRUE,
                      lengthX,
                      lengthY,
                      TRUE)
  du_dsigma1=(u1-u0)/(2*step)
  expect_equal(du_dsigma0,du_dsigma1,tol=10^-11)
})
