# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dst1 <- function(U) {
    .Call('_implicit_dst1', PACKAGE = 'implicit', U)
}

invert <- function(rows, cols, mu, x, b, diffusionType, nIter, tol = 1.0e-10, lengthX = 1, lengthY = 1, preconditionerType = 1L, dirichlet = TRUE, debug = FALSE) {
    .Call('_implicit_invert', PACKAGE = 'implicit', rows, cols, mu, x, b, diffusionType, nIter, tol, lengthX, lengthY, preconditionerType, dirichlet, debug)
}

invert_Irregular <- function(rows, cols, mu, x, b, diffusionType, tol, nIter, internalPoints, dirichlet = TRUE, lengthX = 1, lengthY = 1, preconditionerType = 1L, debug = FALSE) {
    .Call('_implicit_invert_Irregular', PACKAGE = 'implicit', rows, cols, mu, x, b, diffusionType, tol, nIter, internalPoints, dirichlet, lengthX, lengthY, preconditionerType, debug)
}

fick_L_f <- function(mu_, f_, rows, cols, dirichlet = TRUE, lengthX = 1, lengthY = 1) {
    .Call('_implicit_fick_L_f', PACKAGE = 'implicit', mu_, f_, rows, cols, dirichlet, lengthX, lengthY)
}

homogeneous_L_f <- function(f_, rows, cols, dirichlet = TRUE, lengthX = 1, lengthY = 1) {
    .Call('_implicit_homogeneous_L_f', PACKAGE = 'implicit', f_, rows, cols, dirichlet, lengthX, lengthY)
}

general_Homogeneous_Lf <- function(f_, rows, cols, internalPoints_, dirichlet = TRUE, lengthX = 1, lengthY = 1) {
    .Call('_implicit_general_Homogeneous_Lf', PACKAGE = 'implicit', f_, rows, cols, internalPoints_, dirichlet, lengthX, lengthY)
}

general_Fick_Lf <- function(mu_, f_, rows, cols, internalPoints_, dirichlet = TRUE, lengthX = 1, lengthY = 1) {
    .Call('_implicit_general_Fick_Lf', PACKAGE = 'implicit', mu_, f_, rows, cols, internalPoints_, dirichlet, lengthX, lengthY)
}

